repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        name: Check for files larger than 10 MB
        args: [ "--maxkb=10000" ]

      - id: end-of-file-fixer
        name: Ensures blank line at the end of scripts

      - id: trailing-whitespace
        name: Check for trailing whitespaces (auto-fixes)

      - id: pretty-format-json
        name: Formats json files
        args: ['--indent', '2', --no-sort-keys, --autofix]
        files: \.json$

      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ]
        args: ["--select=E,F,W,C90,B,B9,I", "--ignore=E501,B006,C901", "--extend-fixable=B007", "--fix"]
      - id: ruff-format
        types_or: [ python, pyi ]
