from kraken.graphing.models import GraphSettings, GraphType

graph_list: dict[GraphType, GraphSettings] = {
    "aggregation": GraphSettings(
        x_domain="any",
        y_domain="any",
        y_mandatory=False,
        x_agg_mode="non-numeric",
        y_agg=True,
        groups_supported=("colour",),
        facets=False,
        marginals=False,
        hover="none",
        confidence_intervals="data",
        regression=False,
    ),
    "density": GraphSettings(
        x_domain="quantitative_or_temporal",
        y_domain="quantitative",
        y_mandatory=False,
        x_agg_mode=False,
        y_agg=False,
        groups_supported=("colour",),
        facets=False,
        marginals=False,
        hover="none",
        confidence_intervals="none",
        regression=False,
    ),
    "histogram": GraphSettings(
        x_domain="quantitative_or_temporal",
        y_domain=None,
        y_mandatory=False,
        x_agg_mode="numeric",
        y_agg=True,
        groups_supported=("colour",),
        facets=True,
        marginals=False,
        hover="group",
        confidence_intervals="none",
        regression=False,
    ),
    "bar": GraphSettings(
        x_domain="any",
        y_domain="any",
        y_mandatory=False,
        x_agg_mode="non-numeric",
        y_agg=True,
        groups_supported=("colour",),
        facets=True,
        marginals=False,
        hover="group",
        confidence_intervals="figure",
        regression=False,
    ),
    "box": GraphSettings(
        x_domain="any",
        y_domain="quantitative",
        y_mandatory=True,
        x_agg_mode="replace",
        y_agg=False,
        groups_supported=("colour",),
        facets=True,
        marginals=False,
        hover="row",
        confidence_intervals="none",
        regression=False,
    ),
    "violin": GraphSettings(
        x_domain="any",
        y_domain="quantitative",
        y_mandatory=True,
        x_agg_mode="replace",
        y_agg=False,
        groups_supported=("colour",),
        facets=True,
        marginals=False,
        hover="row",
        confidence_intervals="none",
        regression=False,
    ),
    "scatter": GraphSettings(
        x_domain="quantitative_or_temporal",
        y_domain="quantitative",
        y_mandatory=True,
        x_agg_mode=False,
        y_agg=False,
        groups_supported=("colour",),
        facets=True,
        marginals=True,
        hover="row",
        confidence_intervals="none",
        regression=True,
    ),
    "stacked": GraphSettings(
        x_domain="any",
        y_domain="any",
        y_mandatory=False,
        x_agg_mode="non-numeric",
        y_agg=True,
        groups_supported=("colour",),
        facets=True,
        marginals=False,
        hover="group",
        confidence_intervals="none",
        regression=False,
    ),
    "line": GraphSettings(
        x_domain="any",
        y_domain="any",
        y_mandatory=False,
        x_agg_mode="non-numeric",
        y_agg=True,
        groups_supported=("colour",),
        facets=True,
        marginals=False,
        hover="group",
        confidence_intervals="figure",
        regression=False,
    ),
    "area": GraphSettings(
        x_domain="any",
        y_domain="any",
        y_mandatory=False,
        x_agg_mode="non-numeric",
        y_agg=True,
        groups_supported=("colour",),
        facets=False,
        marginals=False,
        hover="none",
        confidence_intervals="none",
        regression=False,
    ),
    "timeline": GraphSettings(
        x_domain="temporal",
        y_domain="any",
        y_mandatory=True,
        x_agg_mode=False,
        y_agg=False,
        groups_supported=("colour",),
        facets=True,
        marginals=False,
        hover="row",
        confidence_intervals="none",
        regression=False,
    ),
}

x_aggs_supported_date = {
    "minute": "min",
    "hour": "h",
    "day": "D",
    "week": "W-SUN",
    "month": "M",
    "year": "Y",
}
y_aggs_supported = {"count", "countd", "sum", "mean", "mode", "median"}
