--$Database = RESEARCH
--$Dataframe = Single
SELECT TOP 1 0
FROM sandbox.INFORMATION_SCHEMA.TABLES
;

--$Dataframe = Multiple
SELECT TOP 1 1 FROM sandbox.INFORMATION_SCHEMA.TABLES
SELECT TOP 1 2 FROM sandbox.INFORMATION_SCHEMA.TABLES
;
